import os
import re
import shutil
import subprocess

import yaml

from app.db.mongodb import get_database
from app.models import ScoredUnit
from app.services.rendercv_mapper import map_to_rendercv_model


async def render_resume(
    compile_id: str, selected_units: list[ScoredUnit], master_version_id: str
) -> str:
    """
    Render resume using RenderCV (Jake's Resume / sb2nov theme).

    1. Get header info from master resume
    2. Map atomic units to RenderCV YAML schema
    3. Generate YAML file
    4. Run 'rendercv render' to produce PDF
    5. Return path to generated PDF
    """
    # Get header info from database
    db = await get_database()

    # Fetch ALL header units
    header_cursor = db.atomic_units.find({"version": master_version_id, "type": "header"})
    header_units = [doc async for doc in header_cursor]
    header_info = extract_header_info(header_units)

    # Create output directory
    output_dir = os.path.abspath(f"output/{compile_id}")
    os.makedirs(output_dir, exist_ok=True)

    # Map to RenderCV Data Model
    cv_data = map_to_rendercv_model(selected_units, header_info)

    # Save as YAML
    yaml_path = os.path.join(output_dir, "cv.yaml")
    with open(yaml_path, "w", encoding="utf-8") as f:
        yaml.dump(cv_data, f, sort_keys=False, allow_unicode=True)

    # Compile with RenderCV (Subprocess)
    # rendercv creates an output folder named 'rendercv_output' usually
    try:
        # We run it inside output_dir so artifacts stay there
        cmd = ["rendercv", "render", "cv.yaml"]

        with open("debug_renderer.log", "w") as log:
            log.write(f"Starting RenderCV in {output_dir}\n")
            log.write(f"YAML Path: {yaml_path}\n")

        result = subprocess.run(cmd, cwd=output_dir, capture_output=True, text=True, check=True)
        print(f"RenderCV Output: {result.stdout}")
        with open("debug_renderer.log", "a") as log:
            log.write("RenderCV Success:\n")
            log.write(result.stdout)
            log.write("\n")

    except subprocess.CalledProcessError as e:
        print(f"RenderCV Failed: {e.stderr}")
        with open("debug_renderer.log", "a") as log:
            log.write("RenderCV FAILED:\n")
            log.write(e.stderr)
            log.write("\n")
            log.write(f"STDOUT: {e.stdout}\n")
        raise RuntimeError(f"RenderCV compilation failed: {e.stderr}")

    # Move/Rename output PDF
    # RenderCV output structure: output_dir/rendercv_output/Name_CV.pdf
    # We want it at output_dir/resume.pdf

    # Find the generated PDF
    found_pdf = None
    rendercv_out = os.path.join(output_dir, "rendercv_output")
    if os.path.exists(rendercv_out):
        for root, _dirs, files in os.walk(rendercv_out):
            for file in files:
                if file.endswith(".pdf"):
                    found_pdf = os.path.join(root, file)
                    break

    target_pdf = os.path.join(output_dir, "resume.pdf")

    if found_pdf and os.path.exists(found_pdf):
        shutil.move(found_pdf, target_pdf)
        # Cleanup
        shutil.rmtree(rendercv_out, ignore_errors=True)
        return target_pdf
    else:
        raise FileNotFoundError(f"PDF not generated by RenderCV. Check logs in {output_dir}")


def extract_header_info(header_units: list[dict]) -> dict:
    """
    Extract name, email, phone, LinkedIn, GitHub from header units.
    Prioritizes structured 'tags' from LLM, then falls back to regex on text.
    """
    if not header_units:
        return {}
        
    info = {
        "name": "Your Name",  # Default if not found
        "email": "",
        "phone": "",
        "linkedin": "",
        "github": "",
    }

    # 1. Try extracted metadata from tags (New Ingestion)
    full_text_parts = []
    
    for unit in header_units:
        # Accumulate text for fallback
        if unit.get("text"):
            full_text_parts.append(unit["text"])
            # If prompt followed, first unit text is Name
            if info["name"] == "Your Name":
                info["name"] = unit["text"]

        # Check tags
        tags = unit.get("tags") or {}
        if isinstance(tags, dict):
            if tags.get("email"): info["email"] = tags["email"]
            if tags.get("phone"): info["phone"] = tags["phone"]
            if tags.get("linkedin"): info["linkedin"] = tags["linkedin"]
            if tags.get("github"): info["github"] = tags["github"]
            
    # 2. Regex Fallback (Old Ingestion or LLM miss)
    full_text = "\n".join(full_text_parts)
    lines = [line.strip() for line in full_text.split("\n") if line.strip()]
    
    # Extract email if missing
    if not info["email"]:
        email_pattern = r"[\w\.-]+@[\w\.-]+\.\w+"
        for line in lines:
            if match := re.search(email_pattern, line):
                info["email"] = match.group(0)
                break
                
    # Extract phone if missing
    if not info["phone"]:
        phone_pattern = r"\(?\d{3}\)?[\s\-\.]?\d{3}[\s\-\.]?\d{4}"
        for line in lines:
            if match := re.search(phone_pattern, line):
                info["phone"] = match.group(0).strip()
                break
                
    # Extract LinkedIn if missing
    if not info["linkedin"]:
        for line in lines:
            if "linkedin.com" in line.lower():
                if match := re.search(r"https?://[^\s]+", line):
                    info["linkedin"] = match.group(0)
                else:
                    clean = line.replace("|", "").strip()
                    for part in clean.split():
                        if "linkedin.com" in part:
                            info["linkedin"] = f"https://{part}" if not part.startswith("http") else part
                            break
                break

    # Extract GitHub if missing
    if not info["github"]:
        for line in lines:
            if "github.com" in line.lower():
                if match := re.search(r"https?://[^\s]+", line):
                    info["github"] = match.group(0)
                else:
                    clean = line.replace("|", "").strip()
                    for part in clean.split():
                        if "github.com" in part:
                            info["github"] = f"https://{part}" if not part.startswith("http") else part
                            break
                break

    return info
